server:
  port: 8081
spring:
  application:
    name: client-paiement
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/client_paiement_bd
    username: postgres
    password: dolzaye
    # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"

    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

topics:
  - client-event-topic
  - paiement-event-topic
  - paiement-transaction-event-topic

springdoc:
  api-docs:
    path: "/api/docs/clientpaiement"